package com.bupt.app.multivrWAP.model;

import java.util.ArrayList;
import java.util.List;

public class WordWAPExample {
	/**
	 * 按日期分表后每张表的日期
	 */
	protected String date;
	/**
	 * 分页查询中的起始记录数
	 */
	protected Integer start;
	/**
	 * 分页查询中的一次查询的记录数
	 */
	protected Integer limit;    
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public WordWAPExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }
    
    public Integer getStart() {
		return start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("keyword is null");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("keyword is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("keyword =", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("keyword <>", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("keyword >", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("keyword >=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("keyword <", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("keyword <=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("keyword like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("keyword not like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordIn(List<String> values) {
            addCriterion("keyword in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotIn(List<String> values) {
            addCriterion("keyword not in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("keyword between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("keyword not between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andPagetypeIsNull() {
            addCriterion("pageType is null");
            return (Criteria) this;
        }

        public Criteria andPagetypeIsNotNull() {
            addCriterion("pageType is not null");
            return (Criteria) this;
        }

        public Criteria andPagetypeEqualTo(Byte value) {
            addCriterion("pageType =", value, "pagetype");
            return (Criteria) this;
        }

        public Criteria andPagetypeNotEqualTo(Byte value) {
            addCriterion("pageType <>", value, "pagetype");
            return (Criteria) this;
        }

        public Criteria andPagetypeGreaterThan(Byte value) {
            addCriterion("pageType >", value, "pagetype");
            return (Criteria) this;
        }

        public Criteria andPagetypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("pageType >=", value, "pagetype");
            return (Criteria) this;
        }

        public Criteria andPagetypeLessThan(Byte value) {
            addCriterion("pageType <", value, "pagetype");
            return (Criteria) this;
        }

        public Criteria andPagetypeLessThanOrEqualTo(Byte value) {
            addCriterion("pageType <=", value, "pagetype");
            return (Criteria) this;
        }

        public Criteria andPagetypeIn(List<Byte> values) {
            addCriterion("pageType in", values, "pagetype");
            return (Criteria) this;
        }

        public Criteria andPagetypeNotIn(List<Byte> values) {
            addCriterion("pageType not in", values, "pagetype");
            return (Criteria) this;
        }

        public Criteria andPagetypeBetween(Byte value1, Byte value2) {
            addCriterion("pageType between", value1, value2, "pagetype");
            return (Criteria) this;
        }

        public Criteria andPagetypeNotBetween(Byte value1, Byte value2) {
            addCriterion("pageType not between", value1, value2, "pagetype");
            return (Criteria) this;
        }

        public Criteria andVridIsNull() {
            addCriterion("vrid is null");
            return (Criteria) this;
        }

        public Criteria andVridIsNotNull() {
            addCriterion("vrid is not null");
            return (Criteria) this;
        }

        public Criteria andVridEqualTo(String value) {
            addCriterion("vrid =", value, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridNotEqualTo(String value) {
            addCriterion("vrid <>", value, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridGreaterThan(String value) {
            addCriterion("vrid >", value, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridGreaterThanOrEqualTo(String value) {
            addCriterion("vrid >=", value, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridLessThan(String value) {
            addCriterion("vrid <", value, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridLessThanOrEqualTo(String value) {
            addCriterion("vrid <=", value, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridLike(String value) {
            addCriterion("vrid like", value, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridNotLike(String value) {
            addCriterion("vrid not like", value, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridIn(List<String> values) {
            addCriterion("vrid in", values, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridNotIn(List<String> values) {
            addCriterion("vrid not in", values, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridBetween(String value1, String value2) {
            addCriterion("vrid between", value1, value2, "vrid");
            return (Criteria) this;
        }

        public Criteria andVridNotBetween(String value1, String value2) {
            addCriterion("vrid not between", value1, value2, "vrid");
            return (Criteria) this;
        }

        public Criteria andLinkidIsNull() {
            addCriterion("linkid is null");
            return (Criteria) this;
        }

        public Criteria andLinkidIsNotNull() {
            addCriterion("linkid is not null");
            return (Criteria) this;
        }

        public Criteria andLinkidEqualTo(Byte value) {
            addCriterion("linkid =", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidNotEqualTo(Byte value) {
            addCriterion("linkid <>", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidGreaterThan(Byte value) {
            addCriterion("linkid >", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidGreaterThanOrEqualTo(Byte value) {
            addCriterion("linkid >=", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidLessThan(Byte value) {
            addCriterion("linkid <", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidLessThanOrEqualTo(Byte value) {
            addCriterion("linkid <=", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidIn(List<Byte> values) {
            addCriterion("linkid in", values, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidNotIn(List<Byte> values) {
            addCriterion("linkid not in", values, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidBetween(Byte value1, Byte value2) {
            addCriterion("linkid between", value1, value2, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidNotBetween(Byte value1, Byte value2) {
            addCriterion("linkid not between", value1, value2, "linkid");
            return (Criteria) this;
        }

        public Criteria andVrposavIsNull() {
            addCriterion("vrposAV is null");
            return (Criteria) this;
        }

        public Criteria andVrposavIsNotNull() {
            addCriterion("vrposAV is not null");
            return (Criteria) this;
        }

        public Criteria andVrposavEqualTo(Float value) {
            addCriterion("vrposAV =", value, "vrposav");
            return (Criteria) this;
        }

        public Criteria andVrposavNotEqualTo(Float value) {
            addCriterion("vrposAV <>", value, "vrposav");
            return (Criteria) this;
        }

        public Criteria andVrposavGreaterThan(Float value) {
            addCriterion("vrposAV >", value, "vrposav");
            return (Criteria) this;
        }

        public Criteria andVrposavGreaterThanOrEqualTo(Float value) {
            addCriterion("vrposAV >=", value, "vrposav");
            return (Criteria) this;
        }

        public Criteria andVrposavLessThan(Float value) {
            addCriterion("vrposAV <", value, "vrposav");
            return (Criteria) this;
        }

        public Criteria andVrposavLessThanOrEqualTo(Float value) {
            addCriterion("vrposAV <=", value, "vrposav");
            return (Criteria) this;
        }

        public Criteria andVrposavIn(List<Float> values) {
            addCriterion("vrposAV in", values, "vrposav");
            return (Criteria) this;
        }

        public Criteria andVrposavNotIn(List<Float> values) {
            addCriterion("vrposAV not in", values, "vrposav");
            return (Criteria) this;
        }

        public Criteria andVrposavBetween(Float value1, Float value2) {
            addCriterion("vrposAV between", value1, value2, "vrposav");
            return (Criteria) this;
        }

        public Criteria andVrposavNotBetween(Float value1, Float value2) {
            addCriterion("vrposAV not between", value1, value2, "vrposav");
            return (Criteria) this;
        }

        public Criteria andPvnumIsNull() {
            addCriterion("pvnum is null");
            return (Criteria) this;
        }

        public Criteria andPvnumIsNotNull() {
            addCriterion("pvnum is not null");
            return (Criteria) this;
        }

        public Criteria andPvnumEqualTo(Integer value) {
            addCriterion("pvnum =", value, "pvnum");
            return (Criteria) this;
        }

        public Criteria andPvnumNotEqualTo(Integer value) {
            addCriterion("pvnum <>", value, "pvnum");
            return (Criteria) this;
        }

        public Criteria andPvnumGreaterThan(Integer value) {
            addCriterion("pvnum >", value, "pvnum");
            return (Criteria) this;
        }

        public Criteria andPvnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("pvnum >=", value, "pvnum");
            return (Criteria) this;
        }

        public Criteria andPvnumLessThan(Integer value) {
            addCriterion("pvnum <", value, "pvnum");
            return (Criteria) this;
        }

        public Criteria andPvnumLessThanOrEqualTo(Integer value) {
            addCriterion("pvnum <=", value, "pvnum");
            return (Criteria) this;
        }

        public Criteria andPvnumIn(List<Integer> values) {
            addCriterion("pvnum in", values, "pvnum");
            return (Criteria) this;
        }

        public Criteria andPvnumNotIn(List<Integer> values) {
            addCriterion("pvnum not in", values, "pvnum");
            return (Criteria) this;
        }

        public Criteria andPvnumBetween(Integer value1, Integer value2) {
            addCriterion("pvnum between", value1, value2, "pvnum");
            return (Criteria) this;
        }

        public Criteria andPvnumNotBetween(Integer value1, Integer value2) {
            addCriterion("pvnum not between", value1, value2, "pvnum");
            return (Criteria) this;
        }

        public Criteria andClicknumIsNull() {
            addCriterion("clicknum is null");
            return (Criteria) this;
        }

        public Criteria andClicknumIsNotNull() {
            addCriterion("clicknum is not null");
            return (Criteria) this;
        }

        public Criteria andClicknumEqualTo(Integer value) {
            addCriterion("clicknum =", value, "clicknum");
            return (Criteria) this;
        }

        public Criteria andClicknumNotEqualTo(Integer value) {
            addCriterion("clicknum <>", value, "clicknum");
            return (Criteria) this;
        }

        public Criteria andClicknumGreaterThan(Integer value) {
            addCriterion("clicknum >", value, "clicknum");
            return (Criteria) this;
        }

        public Criteria andClicknumGreaterThanOrEqualTo(Integer value) {
            addCriterion("clicknum >=", value, "clicknum");
            return (Criteria) this;
        }

        public Criteria andClicknumLessThan(Integer value) {
            addCriterion("clicknum <", value, "clicknum");
            return (Criteria) this;
        }

        public Criteria andClicknumLessThanOrEqualTo(Integer value) {
            addCriterion("clicknum <=", value, "clicknum");
            return (Criteria) this;
        }

        public Criteria andClicknumIn(List<Integer> values) {
            addCriterion("clicknum in", values, "clicknum");
            return (Criteria) this;
        }

        public Criteria andClicknumNotIn(List<Integer> values) {
            addCriterion("clicknum not in", values, "clicknum");
            return (Criteria) this;
        }

        public Criteria andClicknumBetween(Integer value1, Integer value2) {
            addCriterion("clicknum between", value1, value2, "clicknum");
            return (Criteria) this;
        }

        public Criteria andClicknumNotBetween(Integer value1, Integer value2) {
            addCriterion("clicknum not between", value1, value2, "clicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumIsNull() {
            addCriterion("endclicknum is null");
            return (Criteria) this;
        }

        public Criteria andEndclicknumIsNotNull() {
            addCriterion("endclicknum is not null");
            return (Criteria) this;
        }

        public Criteria andEndclicknumEqualTo(Integer value) {
            addCriterion("endclicknum =", value, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumNotEqualTo(Integer value) {
            addCriterion("endclicknum <>", value, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumGreaterThan(Integer value) {
            addCriterion("endclicknum >", value, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumGreaterThanOrEqualTo(Integer value) {
            addCriterion("endclicknum >=", value, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumLessThan(Integer value) {
            addCriterion("endclicknum <", value, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumLessThanOrEqualTo(Integer value) {
            addCriterion("endclicknum <=", value, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumIn(List<Integer> values) {
            addCriterion("endclicknum in", values, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumNotIn(List<Integer> values) {
            addCriterion("endclicknum not in", values, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumBetween(Integer value1, Integer value2) {
            addCriterion("endclicknum between", value1, value2, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andEndclicknumNotBetween(Integer value1, Integer value2) {
            addCriterion("endclicknum not between", value1, value2, "endclicknum");
            return (Criteria) this;
        }

        public Criteria andHourIsNull() {
            addCriterion("hour is null");
            return (Criteria) this;
        }

        public Criteria andHourIsNotNull() {
            addCriterion("hour is not null");
            return (Criteria) this;
        }

        public Criteria andHourEqualTo(Integer value) {
            addCriterion("hour =", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourNotEqualTo(Integer value) {
            addCriterion("hour <>", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourGreaterThan(Integer value) {
            addCriterion("hour >", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("hour >=", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourLessThan(Integer value) {
            addCriterion("hour <", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourLessThanOrEqualTo(Integer value) {
            addCriterion("hour <=", value, "hour");
            return (Criteria) this;
        }

        public Criteria andHourIn(List<Integer> values) {
            addCriterion("hour in", values, "hour");
            return (Criteria) this;
        }

        public Criteria andHourNotIn(List<Integer> values) {
            addCriterion("hour not in", values, "hour");
            return (Criteria) this;
        }

        public Criteria andHourBetween(Integer value1, Integer value2) {
            addCriterion("hour between", value1, value2, "hour");
            return (Criteria) this;
        }

        public Criteria andHourNotBetween(Integer value1, Integer value2) {
            addCriterion("hour not between", value1, value2, "hour");
            return (Criteria) this;
        }

        public Criteria andJhidIsNull() {
            addCriterion("jhid is null");
            return (Criteria) this;
        }

        public Criteria andJhidIsNotNull() {
            addCriterion("jhid is not null");
            return (Criteria) this;
        }

        public Criteria andJhidEqualTo(String value) {
            addCriterion("jhid =", value, "jhid");
            return (Criteria) this;
        }

        public Criteria andJhidNotEqualTo(String value) {
            addCriterion("jhid <>", value, "jhid");
            return (Criteria) this;
        }

        public Criteria andJhidGreaterThan(String value) {
            addCriterion("jhid >", value, "jhid");
            return (Criteria) this;
        }

        public Criteria andJhidGreaterThanOrEqualTo(String value) {
            addCriterion("jhid >=", value, "jhid");
            return (Criteria) this;
        }

        public Criteria andJhidLessThan(String value) {
            addCriterion("jhid <", value, "jhid");
            return (Criteria) this;
        }

        public Criteria andJhidLessThanOrEqualTo(String value) {
            addCriterion("jhid <=", value, "jhid");
            return (Criteria) this;
        }

        public Criteria andJhidIn(List<String> values) {
            addCriterion("jhid in", values, "jhid");
            return (Criteria) this;
        }

        public Criteria andJhidNotIn(List<String> values) {
            addCriterion("jhid not in", values, "jhid");
            return (Criteria) this;
        }

        public Criteria andJhidBetween(String value1, String value2) {
            addCriterion("jhid between", value1, value2, "jhid");
            return (Criteria) this;
        }

        public Criteria andJhidNotBetween(String value1, String value2) {
            addCriterion("jhid not between", value1, value2, "jhid");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(String value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(String value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(String value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(String value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(String value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(String value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLike(String value) {
            addCriterion("date like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotLike(String value) {
            addCriterion("date not like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<String> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<String> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(String value1, String value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(String value1, String value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 22 17:22:14 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_detail_20130921
     *
     * @mbggenerated Sun Sep 22 17:22:14 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }


}