package com.bupt.app.multivrPC.dao;

import com.bupt.app.multivrPC.model.WordPC;
import com.bupt.app.multivrPC.model.WordPCExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordPCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130808
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    int countByExample(WordPCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130808
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    int deleteByExample(WordPCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130808
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    int insert(WordPC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130808
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    int insertSelective(WordPC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130808
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    List<WordPC> selectByExample(WordPCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130808
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    int updateByExampleSelective(@Param("record") WordPC record, @Param("example") WordPCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_detail_20130808
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    int updateByExample(@Param("record") WordPC record, @Param("example") WordPCExample example);
}