package com.bupt.app.multivrPC.model;

public class StatisticsPC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_date.title
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    //private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_date.abtest
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    private Integer abtest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_date.eclpv
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    private Integer eclpv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_date.click
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    private Integer click;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_date.position
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_date.clickid
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    private String clickid;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_date.type
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_detail_date.pv
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    private Integer pv;


    private Integer hour;
    
	//日期
	private String day;
	
	//聚合id
	private String jhid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_date.abtest
     *
     * @return the value of tb_detail_date.abtest
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public Integer getAbtest() {
        return abtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_date.abtest
     *
     * @param abtest the value for tb_detail_date.abtest
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public void setAbtest(Integer abtest) {
        this.abtest = abtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_date.eclpv
     *
     * @return the value of tb_detail_date.eclpv
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public Integer getEclpv() {
        return eclpv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_date.eclpv
     *
     * @param eclpv the value for tb_detail_date.eclpv
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public void setEclpv(Integer eclpv) {
        this.eclpv = eclpv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_date.click
     *
     * @return the value of tb_detail_date.click
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public Integer getClick() {
        return click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_date.click
     *
     * @param click the value for tb_detail_date.click
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public void setClick(Integer click) {
        this.click = click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_date.position
     *
     * @return the value of tb_detail_date.position
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_date.position
     *
     * @param position the value for tb_detail_date.position
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_date.clickid
     *
     * @return the value of tb_detail_date.clickid
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public String getClickid() {
        return clickid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_date.clickid
     *
     * @param clickid the value for tb_detail_date.clickid
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public void setClickid(String clickid) {
        this.clickid = clickid == null ? null : clickid.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_date.type
     *
     * @return the value of tb_detail_date.type
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_date.type
     *
     * @param type the value for tb_detail_date.type
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_detail_date.pv
     *
     * @return the value of tb_detail_date.pv
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_detail_date.pv
     *
     * @param pv the value for tb_detail_date.pv
     *
     * @mbggenerated Fri Aug 23 11:22:06 CST 2013
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

	public Integer getHour() {
		return hour;
	}

	public void setHour(Integer hour) {
		this.hour = hour;
	}

	public String getDay() {
		return day;
	}

	public String getJhid() {
		return jhid;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public void setJhid(String jhid) {
		this.jhid = jhid;
	}
    
    
}